package com.astonm.springbootBaseProject.dao;

import com.astonm.springbootBaseProject.pojo.User;
import org.springframework.stereotype.Repository;

@Repository

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user1
     *
     * @mbggenerated Sat Jul 03 23:20:16 CST 2021
     */
    int updateByPrimaryKey(User record);
}